USE Chocolate_Manufacturing_DW;
GO

CREATE TABLE staging.Equipment_Master_Stage
(
    Equipment_ID                    NVARCHAR(255),
    Asset_Tag                       NVARCHAR(255),
    Equipment_Name                  NVARCHAR(255),
    Equipment_Type                  NVARCHAR(255),
    Category                        NVARCHAR(255),
    Subcategory                     NVARCHAR(255),
    Plant                           NVARCHAR(255),
    Building                        NVARCHAR(255),
    Area                            NVARCHAR(255),
    Production_Line                 NVARCHAR(255),
    Functional_Location             NVARCHAR(255),
    Parent_Equipment                NVARCHAR(255),
    Assembly_Code                   NVARCHAR(255),
    Manufacturer                    NVARCHAR(255),
    Model                           NVARCHAR(255),
    Serial_Number                   NVARCHAR(255),
    Country                         NVARCHAR(255),
    PLC_Brand                       NVARCHAR(255),
    PLC_CPU                         NVARCHAR(255),
    DCS_System                      NVARCHAR(255),
    HMI                             NVARCHAR(255),
    Power_kW                        NVARCHAR(255),
    Voltage_V                       NVARCHAR(255),
    Frequency_Hz                    NVARCHAR(255),
    Installation_Year               NVARCHAR(255),
    Commissioning_Date              NVARCHAR(255),
    Purchase_Cost_USD               NVARCHAR(255),
    Replacement_Cost_USD            NVARCHAR(255),
    Criticality                     NVARCHAR(255),
    Risk_Class                      NVARCHAR(255),
    Status                          NVARCHAR(255),
    PM_Frequency_Days               NVARCHAR(255),
    Calibration_Required            NVARCHAR(255),
    Lubrication_Type                NVARCHAR(255),
    Lubrication_Frequency_Days      NVARCHAR(255),
    MTBF_Hours                      NVARCHAR(255),
    MTTR_Hours                      NVARCHAR(255),
    Warranty_Years                  NVARCHAR(255),
    Expected_Life_Years             NVARCHAR(255),
    Safety_Level                    NVARCHAR(255),
    Energy_Source                   NVARCHAR(255),
    Operating_Shift                 NVARCHAR(255),
    Maintenance_Team                NVARCHAR(255),
    Vendor_Code                     NVARCHAR(255),
    Spare_Parts_Class               NVARCHAR(255),
    Cost_Center                     NVARCHAR(255),
    GPS_Area_Code                   NVARCHAR(255),
    Notes                           NVARCHAR(MAX)
);
GO